name: inwentarz_ee
description: Aplikacja inwentaryzacyjna - Grzegorz Jewusiak /EE.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts:
  firebase_auth:
  firebase_core:
  firebase_storage:
  file_picker:
  permission_handler:

flutter:
  uses-material-design: true

  assets:
    - assets/images/

