// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB-Bf97rZnGfhCkZRuEUhz1_7cNWc4suc',
    appId: '1:354413287546:web:d9b970c0ea349766c203c3',
    messagingSenderId: '354413287546',
    projectId: 'inwentarz-ee',
    authDomain: 'inwentarz-ee.firebaseapp.com',
    storageBucket: 'inwentarz-ee.appspot.com',
    measurementId: 'G-TJE3EESM72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPcY9mQZJuMuTutbkweaNfnyALARrpWQ',
    appId: '1:354413287546:android:420d1dbbec85a3ebc203c3',
    messagingSenderId: '354413287546',
    projectId: 'inwentarz-ee',
    storageBucket: 'inwentarz-ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKk0Brh5pz0XthYkkZaxka2CgRfpFYMnI',
    appId: '1:354413287546:ios:701eb33de80c72b8c203c3',
    messagingSenderId: '354413287546',
    projectId: 'inwentarz-ee',
    storageBucket: 'inwentarz-ee.appspot.com',
    iosClientId: '354413287546-daso4i7hn5mn94baf9k7on14tu76ejrr.apps.googleusercontent.com',
    iosBundleId: 'pl.jewusiak.inwentarzEe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKk0Brh5pz0XthYkkZaxka2CgRfpFYMnI',
    appId: '1:354413287546:ios:701eb33de80c72b8c203c3',
    messagingSenderId: '354413287546',
    projectId: 'inwentarz-ee',
    storageBucket: 'inwentarz-ee.appspot.com',
    iosClientId: '354413287546-daso4i7hn5mn94baf9k7on14tu76ejrr.apps.googleusercontent.com',
    iosBundleId: 'pl.jewusiak.inwentarzEe',
  );
}
